apiVersion: v1
kind: Pod
metadata:
  name: irsa-access-pod
spec:
  serviceAccountName: s3-irsa-access
  containers:
  - image: amazon/aws-cli
    command:
      - "sleep"
      - "600"
    name: awscli
