apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-irsa-access
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/s3-irsa-access
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: s3-irsa-access-rb
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: s3-irsa-access
  namespace: default
